language: python
python:
    - "2.7"
    - "3.3"
env:
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6
install: pip install six Django==$DJANGO_VERSION --use-mirrors
script: django-admin.py test --settings=test_settings --pythonpath=.
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_VERSION=1.4
notifications:
    email:
        - james.p.turk@gmail.com
